; ModuleID = '../bcout/drivers/acpi/acpica/rsinfo.llvm.bc'
source_filename = "drivers/acpi/acpica/rsinfo.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64"

%struct.acpi_rsconvert_info = type { i8, i8, i8, i8 }

@acpi_rs_set_irq = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_dma = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_set_start_dpf = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_end_dpf = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_io = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_fixed_io = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_set_vendor = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_end_tag = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_memory24 = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_memory32 = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_fixed_memory32 = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_address16 = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_address32 = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_address64 = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_ext_address64 = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_ext_irq = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_generic_reg = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_gpio = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_fixed_dma = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_pin_function = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_pin_config = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_pin_group = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_pin_group_function = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_pin_group_config = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_gbl_set_resource_dispatch = dso_local global [25 x %struct.acpi_rsconvert_info*] [%struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_set_irq, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_dma, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_set_start_dpf, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_end_dpf, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_io, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_fixed_io, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_set_vendor, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_end_tag, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_memory24, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_memory32, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_fixed_memory32, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_address16, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_address32, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_address64, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_ext_address64, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_ext_irq, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_generic_reg, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_gpio, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_fixed_dma, i32 0, i32 0), %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_function, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_config, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_group, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_group_function, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_group_config, i32 0, i32 0)], align 16, !dbg !0
@acpi_rs_get_irq = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_get_start_dpf = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_get_vendor_small = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_get_vendor_large = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_gbl_get_resource_dispatch = dso_local global [35 x %struct.acpi_rsconvert_info*] [%struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_get_irq, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_dma, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_get_start_dpf, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_end_dpf, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_io, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_fixed_io, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_fixed_dma, i32 0, i32 0), %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_get_vendor_small, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_end_tag, i32 0, i32 0), %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_memory24, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_generic_reg, i32 0, i32 0), %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_get_vendor_large, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_memory32, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_fixed_memory32, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_address32, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_address16, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_ext_irq, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_address64, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_ext_address64, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_gpio, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_function, i32 0, i32 0), %struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_config, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_group, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_group_function, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_pin_group_config, i32 0, i32 0)], align 16, !dbg !6
@acpi_rs_convert_i2c_serial_bus = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_spi_serial_bus = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_rs_convert_uart_serial_bus = external dso_local global [0 x %struct.acpi_rsconvert_info], align 1
@acpi_gbl_convert_resource_serial_bus_dispatch = dso_local global [4 x %struct.acpi_rsconvert_info*] [%struct.acpi_rsconvert_info* null, %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_i2c_serial_bus, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_spi_serial_bus, i32 0, i32 0), %struct.acpi_rsconvert_info* getelementptr inbounds ([0 x %struct.acpi_rsconvert_info], [0 x %struct.acpi_rsconvert_info]* @acpi_rs_convert_uart_serial_bus, i32 0, i32 0)], align 16, !dbg !24
@acpi_gbl_aml_resource_sizes = dso_local constant [25 x i8] c"\04\03\02\01\08\04\01\02\0C\14\0C\10\1A.8\09\0F\17\06\0C\12\14\0E\11\14", align 16, !dbg !29
@acpi_gbl_resource_struct_sizes = dso_local constant [35 x i8] c"\00\00\00\00\0F\0D\0B\10\0F\0B\0D\00\00\00\0B\10\00\11\14\00\0B\19\110&\1DDB4,%/(,/", align 16, !dbg !35
@acpi_gbl_aml_resource_serial_bus_sizes = dso_local constant [4 x i8] c"\00\12\15\16", align 1, !dbg !38
@acpi_gbl_resource_struct_serial_bus_sizes = dso_local constant [4 x i8] c"\00,03", align 1, !dbg !41

!llvm.dbg.cu = !{!2}
!llvm.module.flags = !{!44, !45, !46, !47}
!llvm.ident = !{!48}

!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression())
!1 = distinct !DIGlobalVariable(name: "acpi_gbl_set_resource_dispatch", scope: !2, file: !3, line: 26, type: !43, isLocal: false, isDefinition: true)
!2 = distinct !DICompileUnit(language: DW_LANG_C89, file: !3, producer: "clang version 10.0.1 (https://github.com/llvm/llvm-project.git ef32c611aa214dea855364efd7ba451ec5ec3f74)", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !4, globals: !5, splitDebugInlining: false, nameTableKind: None)
!3 = !DIFile(filename: "drivers/acpi/acpica/rsinfo.c", directory: "/home/lizy2001/genbc/linux")
!4 = !{}
!5 = !{!0, !6, !24, !29, !35, !38, !41}
!6 = !DIGlobalVariableExpression(var: !7, expr: !DIExpression())
!7 = distinct !DIGlobalVariable(name: "acpi_gbl_get_resource_dispatch", scope: !2, file: !3, line: 56, type: !8, isLocal: false, isDefinition: true)
!8 = !DICompositeType(tag: DW_TAG_array_type, baseType: !9, size: 2240, elements: !22)
!9 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !10, size: 64)
!10 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "acpi_rsconvert_info", file: !11, line: 32, size: 32, elements: !12)
!11 = !DIFile(filename: "drivers/acpi/acpica/acresrc.h", directory: "/home/lizy2001/genbc/linux")
!12 = !{!13, !19, !20, !21}
!13 = !DIDerivedType(tag: DW_TAG_member, name: "opcode", scope: !10, file: !11, line: 33, baseType: !14, size: 8)
!14 = !DIDerivedType(tag: DW_TAG_typedef, name: "u8", file: !15, line: 17, baseType: !16)
!15 = !DIFile(filename: "./include/asm-generic/int-ll64.h", directory: "/home/lizy2001/genbc/linux")
!16 = !DIDerivedType(tag: DW_TAG_typedef, name: "__u8", file: !17, line: 21, baseType: !18)
!17 = !DIFile(filename: "./include/uapi/asm-generic/int-ll64.h", directory: "/home/lizy2001/genbc/linux")
!18 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!19 = !DIDerivedType(tag: DW_TAG_member, name: "resource_offset", scope: !10, file: !11, line: 34, baseType: !14, size: 8, offset: 8)
!20 = !DIDerivedType(tag: DW_TAG_member, name: "aml_offset", scope: !10, file: !11, line: 35, baseType: !14, size: 8, offset: 16)
!21 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !10, file: !11, line: 36, baseType: !14, size: 8, offset: 24)
!22 = !{!23}
!23 = !DISubrange(count: 35)
!24 = !DIGlobalVariableExpression(var: !25, expr: !DIExpression())
!25 = distinct !DIGlobalVariable(name: "acpi_gbl_convert_resource_serial_bus_dispatch", scope: !2, file: !3, line: 101, type: !26, isLocal: false, isDefinition: true)
!26 = !DICompositeType(tag: DW_TAG_array_type, baseType: !9, size: 256, elements: !27)
!27 = !{!28}
!28 = !DISubrange(count: 4)
!29 = !DIGlobalVariableExpression(var: !30, expr: !DIExpression())
!30 = distinct !DIGlobalVariable(name: "acpi_gbl_aml_resource_sizes", scope: !2, file: !3, line: 153, type: !31, isLocal: false, isDefinition: true)
!31 = !DICompositeType(tag: DW_TAG_array_type, baseType: !32, size: 200, elements: !33)
!32 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !14)
!33 = !{!34}
!34 = !DISubrange(count: 25)
!35 = !DIGlobalVariableExpression(var: !36, expr: !DIExpression())
!36 = distinct !DIGlobalVariable(name: "acpi_gbl_resource_struct_sizes", scope: !2, file: !3, line: 181, type: !37, isLocal: false, isDefinition: true)
!37 = !DICompositeType(tag: DW_TAG_array_type, baseType: !32, size: 280, elements: !22)
!38 = !DIGlobalVariableExpression(var: !39, expr: !DIExpression())
!39 = distinct !DIGlobalVariable(name: "acpi_gbl_aml_resource_serial_bus_sizes", scope: !2, file: !3, line: 224, type: !40, isLocal: false, isDefinition: true)
!40 = !DICompositeType(tag: DW_TAG_array_type, baseType: !32, size: 32, elements: !27)
!41 = !DIGlobalVariableExpression(var: !42, expr: !DIExpression())
!42 = distinct !DIGlobalVariable(name: "acpi_gbl_resource_struct_serial_bus_sizes", scope: !2, file: !3, line: 231, type: !40, isLocal: false, isDefinition: true)
!43 = !DICompositeType(tag: DW_TAG_array_type, baseType: !9, size: 1600, elements: !33)
!44 = !{i32 7, !"Dwarf Version", i32 4}
!45 = !{i32 2, !"Debug Info Version", i32 3}
!46 = !{i32 1, !"wchar_size", i32 2}
!47 = !{i32 1, !"Code Model", i32 2}
!48 = !{!"clang version 10.0.1 (https://github.com/llvm/llvm-project.git ef32c611aa214dea855364efd7ba451ec5ec3f74)"}
