; ModuleID = '../bcout/drivers/staging/comedi/drivers/ni_routing/ni_device_routes.llvm.bc'
source_filename = "drivers/staging/comedi/drivers/ni_routing/ni_device_routes.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64"

%struct.ni_device_routes = type { i8*, i32, %struct.ni_route_set* }
%struct.ni_route_set = type { i32, i32, i32* }

@ni_pxi_6030e_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6070e_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6220_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6221_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pxi_6224_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pxi_6225_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6229_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6251_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pxi_6251_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pxie_6251_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6254_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6259_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6534_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6602_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6713_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6723_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pci_6733_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_pxi_6733_device_routes = external dso_local global %struct.ni_device_routes, align 8
@ni_device_routes_list = dso_local constant [19 x %struct.ni_device_routes*] [%struct.ni_device_routes* @ni_pxi_6030e_device_routes, %struct.ni_device_routes* @ni_pci_6070e_device_routes, %struct.ni_device_routes* @ni_pci_6220_device_routes, %struct.ni_device_routes* @ni_pci_6221_device_routes, %struct.ni_device_routes* @ni_pxi_6224_device_routes, %struct.ni_device_routes* @ni_pxi_6225_device_routes, %struct.ni_device_routes* @ni_pci_6229_device_routes, %struct.ni_device_routes* @ni_pci_6251_device_routes, %struct.ni_device_routes* @ni_pxi_6251_device_routes, %struct.ni_device_routes* @ni_pxie_6251_device_routes, %struct.ni_device_routes* @ni_pci_6254_device_routes, %struct.ni_device_routes* @ni_pci_6259_device_routes, %struct.ni_device_routes* @ni_pci_6534_device_routes, %struct.ni_device_routes* @ni_pci_6602_device_routes, %struct.ni_device_routes* @ni_pci_6713_device_routes, %struct.ni_device_routes* @ni_pci_6723_device_routes, %struct.ni_device_routes* @ni_pci_6733_device_routes, %struct.ni_device_routes* @ni_pxi_6733_device_routes, %struct.ni_device_routes* null], align 16, !dbg !0

!llvm.dbg.cu = !{!2}
!llvm.module.flags = !{!28, !29, !30, !31}
!llvm.ident = !{!32}

!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression())
!1 = distinct !DIGlobalVariable(name: "ni_device_routes_list", scope: !2, file: !3, line: 31, type: !6, isLocal: false, isDefinition: true)
!2 = distinct !DICompileUnit(language: DW_LANG_C89, file: !3, producer: "clang version 10.0.1 (https://github.com/llvm/llvm-project.git ef32c611aa214dea855364efd7ba451ec5ec3f74)", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !4, globals: !5, splitDebugInlining: false, nameTableKind: None)
!3 = !DIFile(filename: "drivers/staging/comedi/drivers/ni_routing/ni_device_routes.c", directory: "/home/lizy2001/genbc/linux")
!4 = !{}
!5 = !{!0}
!6 = !DICompositeType(tag: DW_TAG_array_type, baseType: !7, size: 1216, elements: !26)
!7 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !8)
!8 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !9, size: 64)
!9 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ni_device_routes", file: !10, line: 51, size: 192, elements: !11)
!10 = !DIFile(filename: "drivers/staging/comedi/drivers/ni_routing/../ni_routes.h", directory: "/home/lizy2001/genbc/linux")
!11 = !{!12, !16, !18}
!12 = !DIDerivedType(tag: DW_TAG_member, name: "device", scope: !9, file: !10, line: 52, baseType: !13, size: 64)
!13 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !14, size: 64)
!14 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !15)
!15 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!16 = !DIDerivedType(tag: DW_TAG_member, name: "n_route_sets", scope: !9, file: !10, line: 53, baseType: !17, size: 32, offset: 64)
!17 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!18 = !DIDerivedType(tag: DW_TAG_member, name: "routes", scope: !9, file: !10, line: 54, baseType: !19, size: 64, offset: 128)
!19 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !20, size: 64)
!20 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ni_route_set", file: !10, line: 39, size: 128, elements: !21)
!21 = !{!22, !23, !24}
!22 = !DIDerivedType(tag: DW_TAG_member, name: "dest", scope: !20, file: !10, line: 40, baseType: !17, size: 32)
!23 = !DIDerivedType(tag: DW_TAG_member, name: "n_src", scope: !20, file: !10, line: 41, baseType: !17, size: 32, offset: 32)
!24 = !DIDerivedType(tag: DW_TAG_member, name: "src", scope: !20, file: !10, line: 42, baseType: !25, size: 64, offset: 64)
!25 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !17, size: 64)
!26 = !{!27}
!27 = !DISubrange(count: 19)
!28 = !{i32 7, !"Dwarf Version", i32 4}
!29 = !{i32 2, !"Debug Info Version", i32 3}
!30 = !{i32 1, !"wchar_size", i32 2}
!31 = !{i32 1, !"Code Model", i32 2}
!32 = !{!"clang version 10.0.1 (https://github.com/llvm/llvm-project.git ef32c611aa214dea855364efd7ba451ec5ec3f74)"}
